on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      MASTER_REPO: ${{ secrets.MASTER_REPO }}
      JWT_SECRET: ${{ secrets.JWT_SECRET }}
      DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
      EMAIL_USER: ${{ secrets.EMAIL_USER }}
      EMAIL_PASS: ${{ secrets.EMAIL_PASS }}
      STATS_CSV_PATH: ${{ secrets.STATS_CSV_PATH }}
      S3_AWS_ACCESS_KEY_ID: ${{ secrets.S3_AWS_ACCESS_KEY_ID }}
      S3_AWS_SECRET_ACCESS_KEY: ${{ secrets.S3_AWS_SECRET_ACCESS_KEY }}
      DISCORD_CLIENT_ID: ${{ secrets.DISCORD_CLIENT_ID }}
      DISCORD_CLIENT_SECRET: ${{ secrets.DISCORD_CLIENT_SECRET }}
    steps:
      - run: env
      - name: executing remote ssh commands using password
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          port: ${{ secrets.PORT }}
          username: ${{ secrets.USER }}
          key: ${{ secrets.KEY }}
          script: |
            mkdir -p skymp-master-api
            cd skymp-master-api
            mkdir -p $GITHUB_SHA && cd $GITHUB_SHA
            rm -rf .git
            git init
            git remote add origin https://github.com/$MASTER_REPO.git
            git fetch origin $GITHUB_SHA
            git reset --hard FETCH_HEAD
            echo "Please, move docker rm to run_master_api.sh"
            docker rm -f skymp-master-api || true
            JWT_SECRET=$JWT_SECRET DB_PASSWORD=$DB_PASSWORD ./deploy/run_master_api.sh
            docker rmi $(docker images -f "dangling=true" -q) --force || true
            cd ..
            rm -rf $GITHUB_SHA
            echo "it works"
          envs: GITHUB_SHA,MASTER_REPO,JWT_SECRET,DB_PASSWORD,EMAIL_USER,EMAIL_PASS,STATS_CSV_PATH,S3_AWS_ACCESS_KEY_ID,S3_AWS_SECRET_ACCESS_KEY,DISCORD_CLIENT_ID,DISCORD_CLIENT_SECRET
          script_stop: true
          command_timeout: 6h
