on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Pull from ECR
        uses: jwalton/gh-ecr-push@v1
        continue-on-error: true
        with:
          access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          region: eu-west-3
          image: skymp-master-api:latest
          local-image: skymp-master-api
          direction: pull
      - run: docker build --cache-from skymp-master-api --tag skymp-master-api .
      - name: Push to ECR
        uses: jwalton/gh-ecr-push@v1
        with:
          access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          region: eu-west-3
          local-image: skymp-master-api
          image: skymp-master-api:latest
