on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      MASTER_REPO: ${{ secrets.MASTER_REPO }}
    steps:
      - name: executing remote ssh commands using password
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          port: ${{ secrets.PORT }}
          username: ${{ secrets.USER }}
          key: ${{ secrets.KEY }}
          script: |
            mkdir -p skymp-master-api
            cd skymp-master-api
            mkdir -p $GITHUB_SHA && cd $GITHUB_SHA
            rm -rf .git
            git init
            git remote add origin https://github.com/$MASTER_REPO.git
            git fetch origin $GITHUB_SHA
            git reset --hard FETCH_HEAD
            echo "Please, move docker rm to run_master_api.sh"
            docker rm -f skymp-master-api || true
            #chmod 777 ./deploy/run_master_api.sh
            #./deploy/run_master_api.sh
            docker rmi $(docker images -f "dangling=true" -q) --force || true
            rm -rf $GITHUB_SHA
            echo "it works"
          envs: GITHUB_SHA,MASTER_REPO
          script_stop: true
          command_timeout: 6h
